project:
  type: website
  output-dir: docs

website:
  title: "April Shelhon"
 

  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: test.qmd
        text: volunteer service

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: visual

