project:
  type: website
  output-dir: docs

website:
  title: "April Shelhon"
  image: 
about: 
  template: solana
  image-shape: rounded
  image-width: 15em
  links:
    - text: LinkedIn
      href: 
    - text: GitHub
      href: https://github.com/konadog
    - text: Email
      href: april.shelhon@colostate.edu
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

